insert into institutions (id, code, name, chief, secretary, treasurer, commission, gender_access, status_access, status)
values  (2, 'MU.Ra', 'Raudlatul Athfal', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '2', '1', 0),
        (3, 'MU.Ida', 'Tarbiyah I''dadiyah Putra', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '1', 0),
        (4, 'MU.Idi', 'Tarbiyah I''dadiyah Putri', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '1', 0),
        (5, 'MU.Mda', 'Madrasah Ibtidaiyah Putra', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '1', 0),
        (6, 'MU.Mdi', 'Madrasah Ibtidaiyah Putri', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '1', 0),
        (7, 'MU.Mdp', 'Madrasah Diniyah Palengaan', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '2', '1', 0),
        (8, 'MU.Mta', 'Madrasah Tsanawiyah Putra', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '1', 0),
        (9, 'MU.Mti', 'Madrasah Tsanawiyah Putri', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '1', 0),
        (10, 'MU.Ata', 'Madrasah Aliyah Putra', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '1', 0),
        (11, 'MU.Ati', 'Madrasah Aliyah Putri', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '1', 0),
        (12, 'MU.Pad', 'Pendidikan Anak Usia Dini', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '2', '2', 0),
        (13, 'MU.Tka', 'Taman Kanak-Kanak', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '2', '2', 0),
        (14, 'MU.Mis', 'Madrasah Ibtidaiyah Hukumiyah', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '2', '2', 0),
        (15, 'MU.Smp', 'SMP Plus', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '2', 0),
        (16, 'MU.Mts', 'Madrasah Tsanawiyah', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '2', 0),
        (17, 'MU.Map', 'Madrasah Aliyah', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '2', 0),
        (18, 'MU.Smk', 'SMK Miftahul Ulum', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '1', '2', 0),
        (19, 'WH.Ma', 'MA Wachid Hasyim', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '2', 0),
        (20, 'WH.Smk', 'SMK Wachid Hasyim', 'null', 'null', 'null', 'BIDANG MADRASIYAH', '0', '2', 0),
        (21, 'IAIMU', 'Perguruan Tinggi', 'null', 'null', 'null', 'KHUSUS', '2', '2', 0),
        (22, 'EKS', 'Tidak sekolah/Lembaga Non Kebun Baru', 'null', 'null', 'null', 'KHUSUS', '2', '0', 0),
        (23, 'U-101', 'Staf Sekretaris Putra', 'null', 'null', 'null', 'UMUM', '0', '0', 0);