insert into provinces (id, name)
values  ('1', 'Aceh'),
        ('10', 'Jawa Barat'),
        ('11', 'Jawa Tengah'),
        ('12', 'Jawa Timur'),
        ('13', 'Kalimantan Barat'),
        ('14', 'Kalimantan Selatan'),
        ('15', 'Kalimantan Tengah'),
        ('16', 'Kalimantan Timur'),
        ('17', 'Kalimantan Utara'),
        ('18', 'Kepulauan Riau'),
        ('19', 'Lampung'),
        ('2', 'Bali'),
        ('20', 'Maluku'),
        ('21', 'Maluku Utara'),
        ('22', 'Nusa Tenggara Barat'),
        ('23', 'Nusa Tenggara Timur'),
        ('24', 'Papua'),
        ('25', 'Papua Barat'),
        ('26', 'Riau'),
        ('27', 'Sulawesi Barat'),
        ('28', 'Sulawesi Selatan'),
        ('29', 'Sulawesi Tengah'),
        ('3', 'Bangka Belitung'),
        ('30', 'Sulawesi Tenggara'),
        ('31', 'Sulawesi Utara'),
        ('32', 'Sumatera Barat'),
        ('33', 'Sumatera Selatan'),
        ('34', 'Sumatera Utara'),
        ('4', 'Banten'),
        ('5', 'Bengkulu'),
        ('6', 'DI Yogyakarta'),
        ('7', 'DKI Jakarta'),
        ('8', 'Gorontalo'),
        ('9', 'Jambi');